meta_product_name: "Astrocrush"
meta_title: "Astrocrush - Your sign, your soul mate"
meta_description: "Meet the right partner using astrological compatibility!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
